n=int(input("enter n"))
q=n//2000
if(q!=0):
    print(q,"two thousand rupee",end=' ')
n=n%2000
q=n//500
if(q!=0):
    print(q,"five hundered rupee",end=' ')
n=n%500
q=n//200
if(q!=200):
    print(q,"two hundered rupee",end=' ')
n=n%200
q=n//100
if q!=100:
    print(q,"one hundered rupee",end=' ')
n=n%100
q=n//50
if q!=50:
    print(q,"fifty rupee",end=' ')
n=n%50
q=n//10
if q!=10:
    print(q,"ten rupee",end=' ')
n=n%10
q=n//5
if q!=5:
    print(q,"five rupee",end=' ')
n=n%5
q=n//1
if q!=1:
    print(q,"one rupee",end=' ')
